# Generated by Django 2.2.10 on 2021-11-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211113_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='choice',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ManyToManyField(related_name='answers', to='api.Choice', verbose_name='Вариант ответа'),
        ),
    ]
