# Generated by Django 2.2.10 on 2021-11-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211113_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ManyToManyField(blank=True, null=True, related_name='answers', to='api.Choice', verbose_name='Вариант ответа'),
        ),
    ]
